# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [1]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

Using TensorFlow backend.


# 資料準備

In [3]:
(x_img_train,y_label_train), \
(x_img_test, y_label_test)=cifar100.load_data()

169009152/169001437 [==============================] - 85s 1us/step


In [ ]:
print('train:',len(x_img_train))
print('test :',len(x_img_test))

# Image normalize 

In [7]:
x_img_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [8]:
x_img_train_normalize = x_img_train.astype('float32') / 255.0
x_img_test_normalize = x_img_test.astype('float32') / 255.0

In [9]:
x_img_train_normalize[0][0][0]

array([1., 1., 1.], dtype=float32)

# 轉換label 為OneHot Encoding

In [10]:
y_label_train.shape

(50000, 1)

In [11]:
y_label_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])